### ISSUE TITLE
Add Travis CI Integration

### ISSUE THREAD

**Issue by kevgathuku** [AndelaOSP/slcon-mentor#1]
**Problem:**
- We do not have Continuous Testing for this project, so we cannot know if new code will break the project.

**Solution:**
Add Continuous Testing with [Travis CI](travis-ci.org)

**Comment by andela-anandaa** [comment]
I like the way you break down the issues by *Problem / Solution* 👍

**Comment by kevgathuku** [comment]
Thanks @andela-anandaa 
I see this approach being best since it forces people to suggest solutions and work on things that are actual problems.
