### ISSUE TITLE
Split settings for different environments

### ISSUE THREAD

**Issue by kevgathuku** [AndelaOSP/slcon-mentor#2]
**Problem:**
All the environments are sharing a single `settings.py` file.

**Solution**
Every environment should have its own settings file, and there should be a base settings file that each environment should extend.
Convert the settings from a module (single file) to a package with the following folder structure:
```
settings
├── __init__.py
├── base.py
├── local.py
├── prod.py
└── test.py
```

**Comment by JoanNgatia** [comment]
This was worked on in this  [PR]((https://github.com/AndelaOSP/slcon-mentor/pull/9)
