### ISSUE TITLE
Add Travis CI badge to README

### ISSUE THREAD

**Issue by kevgathuku** [AndelaOSP/slcon-mentor#6]
**Problem:**
There is no way to immediately know the build status of the project

**Solution:**
Add a build status badge in the README

**Comment by faraazahmad** [comment]
Hi, I'm interested in tackling this issue. I've read [this tutorial](https://docs.travis-ci.com/user/status-images/) and it seems like I would need the image URL of this repo.
I'd like to know where I can get it.
Thanks.

**Comment by kevgathuku** [comment]
Hi @faraazahmad we would love your contribution. You can find the image URL for the repo here: 
https://travis-ci.org/AndelaOSP/slcon-mentor

**Comment by faraazahmad** [comment]
I've created a [Pull Request](https://github.com/AndelaOSP/slcon-mentor/pull/10) with the Travis CI badge. 
I hope it's right.
Cheers.

**Comment by kevgathuku** [comment]
It is right @faraazahmad. Thanks for contributing.
Feel free to pick up any other issue to work on.
We are currently discussing development of this project at https://andelaosp.slack.com
Would you like for me to send you an invite?

**Comment by faraazahmad** [comment]
Sure, I'd be glad to be of any help.

**Comment by kevgathuku** [comment]
Please send me your email address on kevin.ndungu@andela.com and I'll send you the invite.

**Comment by faraazahmad** [comment]
Hi, here's my email ID.
faraaz98@live.com



On 28 Jan 2017 12:18 am, kevgathuku <notifications@github.com> wrote:

Please send me your email address on kevin.ndungu@andela.com<mailto:kevin.ndungu@andela.com> and I'll send you the invite.

**Comment by JoanNgatia** [comment]
This was worked on [here](https://github.com/AndelaOSP/slcon-mentor/pull/10)
